spring:
  application:
    name: grpc-service
  main:
    allow-circular-references: true
server:
  port: 8001
grpc:
  server:
    port: 9001
    reflection-service-enabled: true
  client:
    address-client:
      address: static://localhost:9002
      negotiationType: plaintext

