spring:
  application:
    name: assignment-1

  datasource:
    url: jdbc:mysql://localhost:3306/dummy
    username: root
    password: 2799

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
         format_sql: true


