syntax = "proto3";
option java_multiple_files = true;
option java_outer_classname = "EmployeeProtoBufService";
option java_package = "com.tutorial.grpc_employee";

message EmployeeProto{
  int32 empId = 1;
  string empName = 2;
  Address address = 3;
}

message Address{
  int32 empId = 1;
  string address = 2;
}
message EmployeeRequest{
  int32 empId = 1;
}

message EmployeeResponse{
  EmployeeProto employee = 1;
}
message EmployeeListResponse{
  repeated EmployeeProto employeeList = 1;
}
message AddressRequest{
  int32 empId = 1;
}
message AddressAllResponse{
  repeated Address address = 1;
}
message Empty{}
service EmployeeService{
  rpc getEmployee(EmployeeRequest) returns (EmployeeResponse);
  rpc getAllEmployee(Empty) returns (stream EmployeeResponse);
  rpc getEmployeeWithAddress(EmployeeRequest) returns (EmployeeResponse);
  rpc getAllEmployeeWithAddress(Empty) returns (stream EmployeeResponse);
}
service AddressService{
  rpc getAddressById(AddressRequest) returns (Address);
  rpc getListOfAddress(Empty) returns (AddressAllResponse);
  rpc getAllAddress(Empty) returns (stream Address);
  rpc getListOfEmployeeWithAddress(Empty) returns (EmployeeListResponse);
  rpc sendListEmployeeToAddress(stream EmployeeProto) returns (stream EmployeeProto);
}