spring:
  application:
    name: output-service
grpc:
  client:
    movie-service:
      address: 'static://localhost:9001'
      negotiation-type: PLAINTEXT
springdoc:
  swagger-ui:
    path: videobuf-doc
  api-docs:
    path: videobuf-json/doc