spring:
  application:
    name: transaction-tutorial
  datasource:
    url: jdbc:mysql://localhost:3306/testing
    username: vb
    password: 12345678

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
