spring:
  application:
    name: transaction-tutorial
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/vb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
